name: 'Compile'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.9.2
    steps:
      - name: Install Make
        run: apk add --no-cache make
      - name: Run Make
        run: make all
