name: 'Compile'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex:2.9.2
      volumes:
        - ./:/data
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Make
        run: apk add --no-cache make
      - name: Run Make
        run: make all
      - name: Upload dist
        uses: actions/upload-artifact@v3
        with:
          name: book-dist
          path: dist/
